name: Library Release CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - 'NOTICE.txt'
    - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Publish
      run: |
        gradle wrapper --gradle-version 6.7.1
        ./gradlew :hidden-api:build
        ./gradlew :library:publish
        
    - name: Upload maven repo
      uses: actions/upload-artifact@v2
      with:
        name: lib-release
        path: local-mvn-repo

    - name: Upload mappings
      uses: actions/upload-artifact@v2
      with:
        name: lib-mapping
        path: library/build/outputs/mapping
