name: Library Release CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - 'NOTICE.txt'
    - 'LICENSE'
    - '.github/workflows/test.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '.github/workflows/test.yml'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Publish
      env:
        GRADLE_VER: 6.7.1
      run: |
        gradle :wrapper --gradle-version $env:GRADLE_VER
        ./gradlew :hidden-api:build
        ./gradlew :library:publish
        
    - name: Upload maven repo
      uses: actions/upload-artifact@v2
      with:
        name: lib-release
        path: local-mvn-repo

    - name: Upload mappings
      uses: actions/upload-artifact@v2
      with:
        name: lib-mapping
        path: library/build/outputs/mapping