name: Library Test CI

on:
  push:
    branches: [ master ]
    paths:
    - 'library/**'
    - '.github/workflows/test.yml'
  pull_request:
    branches: [ master ]
    paths:
    - 'library/**'
    - '.github/workflows/test.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Execute unit test
      env:
        GRADLE_VER: 7.2
      run: |
        gradle wrapper --gradle-version $GRADLE_VER
        ./gradlew :hidden-api:build
        ./gradlew :library:testDebugUnitTest
        
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: lib-unit-test-report
        path: library/build/reports/tests/testDebugUnitTest